# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(394, 535)
        self.label = QtWidgets.QLabel(login_window)
        self.label.setGeometry(QtCore.QRect(10, 20, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login_window)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semiligh")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.number_edit = QtWidgets.QLineEdit(login_window)
        self.number_edit.setGeometry(QtCore.QRect(10, 210, 375, 30))
        self.number_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.number_edit.setObjectName("number_edit")
        self.email_edit = QtWidgets.QLineEdit(login_window)
        self.email_edit.setGeometry(QtCore.QRect(10, 260, 375, 30))
        self.email_edit.setText("")
        self.email_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.email_edit.setObjectName("email_edit")
        self.login_button = QtWidgets.QPushButton(login_window)
        self.login_button.setGeometry(QtCore.QRect(290, 360, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semilig")
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.sign_up = QtWidgets.QPushButton(login_window)
        self.sign_up.setGeometry(QtCore.QRect(170, 420, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        self.sign_up.setFont(font)
        self.sign_up.setObjectName("sign_up")
        self.label_3 = QtWidgets.QLabel(login_window)
        self.label_3.setGeometry(QtCore.QRect(10, 420, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.name_edit = QtWidgets.QLineEdit(login_window)
        self.name_edit.setGeometry(QtCore.QRect(10, 160, 375, 30))
        self.name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.name_edit.setObjectName("name_edit")
        self.product_edit = QtWidgets.QLineEdit(login_window)
        self.product_edit.setGeometry(QtCore.QRect(10, 310, 375, 30))
        self.product_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.product_edit.setObjectName("product_edit")
        self.sign_up.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.number_edit.raise_()
        self.email_edit.raise_()
        self.login_button.raise_()
        self.label_3.raise_()
        self.name_edit.raise_()
        self.product_edit.raise_()

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "PricePulse"))
        self.label.setText(_translate("login_window", "Sign Up"))
        self.label_2.setText(_translate("login_window", "Please sign up to continue"))
        self.number_edit.setPlaceholderText(_translate("login_window", "Number"))
        self.email_edit.setPlaceholderText(_translate("login_window", "Email address"))
        self.login_button.setText(_translate("login_window", "Sign Up"))
        self.sign_up.setText(_translate("login_window", "here"))
        self.label_3.setText(_translate("login_window", "Activate your 2 day free trial"))
        self.name_edit.setPlaceholderText(_translate("login_window", "Full Name"))
        self.product_edit.setPlaceholderText(_translate("login_window", "Product key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QWidget()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
