# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trial_window(object):
    def setupUi(self, trial_window):
        trial_window.setObjectName("trial_window")
        trial_window.resize(394, 395)
        self.label = QtWidgets.QLabel(trial_window)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(trial_window)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semiligh")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.number_edit = QtWidgets.QLineEdit(trial_window)
        self.number_edit.setGeometry(QtCore.QRect(10, 210, 375, 30))
        self.number_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.number_edit.setObjectName("number_edit")
        self.email_edit = QtWidgets.QLineEdit(trial_window)
        self.email_edit.setGeometry(QtCore.QRect(10, 260, 375, 30))
        self.email_edit.setText("")
        self.email_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.email_edit.setObjectName("email_edit")
        self.login_button = QtWidgets.QPushButton(trial_window)
        self.login_button.setGeometry(QtCore.QRect(280, 310, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semilig")
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.name_edit = QtWidgets.QLineEdit(trial_window)
        self.name_edit.setGeometry(QtCore.QRect(10, 160, 375, 30))
        self.name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.name_edit.setObjectName("name_edit")

        self.retranslateUi(trial_window)
        QtCore.QMetaObject.connectSlotsByName(trial_window)

    def retranslateUi(self, trial_window):
        _translate = QtCore.QCoreApplication.translate
        trial_window.setWindowTitle(_translate("trial_window", "PricePulse"))
        self.label.setText(_translate("trial_window", "Try it out"))
        self.label_2.setText(_translate("trial_window", "Two day free trial"))
        self.number_edit.setPlaceholderText(_translate("trial_window", "Number"))
        self.email_edit.setPlaceholderText(_translate("trial_window", "Email address"))
        self.login_button.setText(_translate("trial_window", "Sign Up"))
        self.name_edit.setPlaceholderText(_translate("trial_window", "Full Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trial_window = QtWidgets.QWidget()
    ui = Ui_trial_window()
    ui.setupUi(trial_window)
    trial_window.show()
    sys.exit(app.exec_())
